export const phrasesSample = [
  {
    id: '1',
    phrase: 'How have you been?',
    meaning: 'Dạo này bạn thế nào?',
    example: 'Long time no see! How have you been?',
    exampleTranslation: 'Lâu rồi không gặp! Dạo này bạn thế nào?',
    category: 'Chào hỏi',
  },
  {
    id: '2',
    phrase: "I couldn't agree more.",
    meaning: 'Tôi hoàn toàn đồng ý.',
    example: 'That movie was amazing. I couldn\'t agree more.',
    exampleTranslation: 'Bộ phim đó thật tuyệt vời. Tôi hoàn toàn đồng ý.',
    category: 'Đồng ý',
  },
  {
    id: '3',
    phrase: 'It slipped my mind.',
    meaning: 'Tôi quên mất.',
    example: 'I was supposed to call you yesterday, but it slipped my mind.',
    exampleTranslation: 'Đáng lẽ tôi phải gọi cho bạn hôm qua, nhưng tôi quên mất.',
    category: 'Xin lỗi',
  },
  {
    id: '4',
    phrase: "I'll get back to you on that.",
    meaning: 'Tôi sẽ trả lời bạn sau về việc đó.',
    example: 'I need to check my schedule first. I\'ll get back to you on that.',
    exampleTranslation: 'Tôi cần kiểm tra lịch trình trước. Tôi sẽ trả lời bạn sau về việc đó.',
    category: 'Công việc',
  },
  {
    id: '5',
    phrase: "It's on the tip of my tongue.",
    meaning: 'Tôi suýt nhớ ra rồi (ý nói gần như nhớ ra điều gì đó).',
    example: "What's the name of that actor? It's on the tip of my tongue.",
    exampleTranslation: 'Tên của diễn viên đó là gì nhỉ? Tôi suýt nhớ ra rồi.',
    category: 'Giao tiếp hàng ngày',
  },
  {
    id: '6',
    phrase: "Let's call it a day.",
    meaning: 'Hãy kết thúc công việc hôm nay.',
    example: "We've been working for hours. Let's call it a day and continue tomorrow.",
    exampleTranslation: 'Chúng ta đã làm việc nhiều giờ rồi. Hãy kết thúc hôm nay và tiếp tục vào ngày mai.',
    category: 'Công việc',
  },
  {
    id: '7',
    phrase: 'That rings a bell.',
    meaning: 'Điều đó nghe quen quen.',
    example: "That name rings a bell, but I can't remember where I've heard it before.",
    exampleTranslation: 'Cái tên đó nghe quen quen, nhưng tôi không nhớ đã nghe nó ở đâu trước đây.',
    category: 'Giao tiếp hàng ngày',
  },
  {
    id: '8',
    phrase: "I'm all ears.",
    meaning: 'Tôi đang lắng nghe đây.',
    example: 'You wanted to tell me something important? I\'m all ears.',
    exampleTranslation: 'Bạn muốn nói với tôi điều gì đó quan trọng? Tôi đang lắng nghe đây.',
    category: 'Giao tiếp hàng ngày',
  },
]; 